#!/command/with-contenv sh

# Confd can request a reload as soon as its initial template is written. Start
# watching only after nginx is able to receive that signal.
until pidof nginx >/dev/null; do
    sleep 1
done

exec /opt/wodby/tools/bin/confd \
    -backend etcdv3 \
    -node "http://${WODBY_ETCD_HOST:-etcd.wodby}:${WODBY_ETCD_PORT:-2379}" \
    -watch
