#!/bin/sh

set -e

if [[ -n "${DEBUG}" ]]; then
    set -x
fi

dh_file=/mnt/containers/edge/dhparam.pem

if [[ ! -f "${dh_file}" ]]; then
    openssl dhparam -out "${dh_file}" 2048
    chmod 400 "${dh_file}"
fi

cp "${dh_file}" /etc/nginx/pki/dhparam.pem