#!/usr/bin/with-contenv bash

set -eo pipefail

if [[ ! -f /mnt/containers/edge/dhparam.pem ]]; then
    openssl dhparam -out /tmp/dhparam.pem 2048
    mv /tmp/dhparam.pem /mnt/containers/edge/dhparam.pem
    chmod 400 /mnt/containers/edge/dhparam.pem
fi

cp /mnt/containers/edge/dhparam.pem /etc/nginx/pki/dhparam.pem