#!/usr/bin/with-contenv bash

set -eo pipefail

if [[ ! -f /mnt/containers/edge/ssl.key ]]; then
    openssl req -newkey rsa:4096 -days 3650 -nodes -x509 \
      -subj "/C=US/ST=California/L=Sunnyvale/O=Wodby/CN=Wodby/emailAddress=hello@wodby.com" \
      -keyout /tmp/ssl.key \
      -out /tmp/ssl.crt

    mv /tmp/ssl.key /mnt/containers/edge/ssl.key
    mv /tmp/ssl.crt /mnt/containers/edge/ssl.crt
    chmod 400 /mnt/containers/edge/ssl.key
    chmod 400 /mnt/containers/edge/ssl.crt
fi

mkdir -p /etc/nginx/ssl

domain="node-${WODBY_NODE_UUID}.${WODBY_BASE_DOMAIN:-wodby.cloud}"

if [[ -f /mnt/containers/edge/certificates/"${domain}".key ]]; then
  cp /mnt/containers/edge/certificates/"${domain}".key /etc/nginx/ssl/default.key
  cp /mnt/containers/edge/certificates/"${domain}".crt /etc/nginx/ssl/default.crt
else
  cp /mnt/containers/edge/ssl.key /etc/nginx/ssl/default.key
  cp /mnt/containers/edge/ssl.crt /etc/nginx/ssl/default.crt
fi